/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.giangvienui;

import dao.DangKyDayDAO;
import dao.GiangVienDAO;
import dao.SinhVienDAO;
import entity.DangKyDay;
import entity.GiangVien;
import entity.LopHocPhan;
import entity.SinhVien;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableRowSorter;
import model.SinhVienTableModel;
import util.LoginContext;
import util.MessageBox;

/**
 *
 * @author cuong
 */
public class XemDSSinhVien extends javax.swing.JPanel {

  /**
   * Creates new form XemDSSinhVien
   */
  private final DangKyDayDAO dkddao;
  private final SinhVienDAO svdao;
  private final GiangVienDAO gvdao;
  private TableRowSorter<SinhVienTableModel> sorter;

  public XemDSSinhVien() {
    initComponents();
    dkddao = new DangKyDayDAO();
    svdao = new SinhVienDAO();
    gvdao = new GiangVienDAO();
    load();
    filterText.getDocument().addDocumentListener(new DocumentListener() {
      @Override
      public void insertUpdate(DocumentEvent e) {
        onFilter();
      }

      @Override
      public void removeUpdate(DocumentEvent e) {
        onFilter();
      }

      @Override
      public void changedUpdate(DocumentEvent e) {
        onFilter();
      }
    });
  }

  private void load() {
    try {
      GiangVien gv = gvdao.get(LoginContext.getUser().getUsername());
      List<LopHocPhan> dslhp = dkddao.getAllOfTeacher(gv).stream().map(DangKyDay::getLopHocPhan).collect(Collectors.toList());
      DefaultComboBoxModel<LopHocPhan> dslhpBoxModel = new DefaultComboBoxModel<>(new Vector<>(dslhp));
      lhpCombo.setModel(dslhpBoxModel);
    } catch (Exception e) {
      MessageBox.showErrorMessage(this, e.getMessage());
    }
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    lhpCombo = new javax.swing.JComboBox<>();
    jLabel3 = new javax.swing.JLabel();
    filterByCombo = new javax.swing.JComboBox<>();
    filterText = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    svTb = new javax.swing.JTable();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel1.setText("DANH SÁCH SINH VIÊN");

    jLabel2.setText("Chọn một lớp học phần:");

    lhpCombo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        lhpComboActionPerformed(evt);
      }
    });

    jLabel3.setText("Tìm kiếm:");

    filterByCombo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        filterByComboActionPerformed(evt);
      }
    });

    svTb.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null}
      },
      new String [] {
        "Mã sinh viên", "Học tên", "Ngày sinh", "Giới tính", "Địa chỉ", "Số điện thoại"
      }
    ));
    jScrollPane1.setViewportView(svTb);

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/search.png"))); // NOI18N
    jButton1.setText("Xem");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/refresh.png"))); // NOI18N
    jButton2.setText("Làm mới");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filterByCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterText))
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lhpCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jButton1)
            .addGap(18, 18, 18)
            .addComponent(jButton2)
            .addGap(0, 269, Short.MAX_VALUE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jLabel1)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(23, 23, 23)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jButton1)
            .addComponent(jButton2))
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabel2)
            .addComponent(lhpCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(filterByCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(filterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void onFilter() {
    String text = filterText.getText();
    if (sorter == null) {
      return;
    }
    sorter.setRowFilter(RowFilter.regexFilter(text, filterByCombo.getSelectedIndex()));
  }
  private void filterByComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterByComboActionPerformed

  }//GEN-LAST:event_filterByComboActionPerformed

  private void lhpComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lhpComboActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_lhpComboActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
      List<SinhVien> dssv = svdao.getAllStudentOfClass((LopHocPhan) lhpCombo.getSelectedItem());
      SinhVienTableModel model = new SinhVienTableModel(dssv);
      svTb.setModel(model);
      filterByCombo.setModel(new DefaultComboBoxModel<>(new Vector<>(model.getHeaders())));
      sorter = new TableRowSorter<>(model);
      // TODO add your handling code here:
    } catch (SQLException ex) {
      MessageBox.showErrorMessage(this, ex.getMessage());
    }    // TODO add your handling code here:
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    load();
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton2ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox<String> filterByCombo;
  private javax.swing.JTextField filterText;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JComboBox<LopHocPhan> lhpCombo;
  private javax.swing.JTable svTb;
  // End of variables declaration//GEN-END:variables
}
