/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.adminui;

import dao.ChuongTrinhDAO;
import dao.HocPhanDAO;
import dao.NganhDAO;
import entity.ChuongTrinh;
import entity.HocPhan;
import entity.Nganh;
import java.awt.Graphics;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableRowSorter;
import model.HocPhanTableModel;
import util.MessageBox;

/**
 *
 * @author chung
 */
public class QlhpPanel extends javax.swing.JPanel {

  /**
   * Creates new form QlhpPanel
   */
  private final HocPhanDAO hpdao;
  private final NganhDAO ndao;
  private final ChuongTrinhDAO ctdao;
  private HocPhanTableModel hpModel;
  private TableRowSorter<HocPhanTableModel> rowSorter;
  private List<JCheckBox> dsNganhCB;
  private List<Nganh> dsNganh;

  public QlhpPanel() {
    initComponents();
    hpdao = new HocPhanDAO();
    ndao = new NganhDAO();
    ctdao=new ChuongTrinhDAO();
    hocPhanTb.getSelectionModel().addListSelectionListener(e -> onRowClick());
    keyTf.getDocument().addDocumentListener(new DocumentListener() {
      @Override
      public void insertUpdate(DocumentEvent arg0) {
        onFiltering();
      }

      @Override
      public void removeUpdate(DocumentEvent arg0) {
        onFiltering();
      }

      @Override
      public void changedUpdate(DocumentEvent arg0) {
        onFiltering();
      }
    });
    load();
  }

  private void onRowClick() {
    int row = hocPhanTb.getSelectedRow();
    if (row == -1) {
      return;
    }
    HocPhan hp = hpModel.getRowAt(row);
    mahpTf.setText(hp.getMaHP());
    mahpTf.setEnabled(false);
    mahptdCombo.setSelectedItem(hp.getHptd());
    tenhpTf.setText(hp.getTenHP());
    motaTf.setText(hp.getMoTa());
    ppdgTf.setText(hp.getPpdg());
    sotcSpinner.setValue(hp.getSoTC());
    batBuocCheckbox.setSelected(hp.isBatBuoc());
    dsNganhCB.forEach(cb -> cb.setSelected(false));
    hp.getDsNganh().forEach(n -> {
      dsNganhCB.get(dsNganh.indexOf(n)).setSelected(true);
    });
  }
  
  private void load() {
    try {
      List<HocPhan> dsHp = hpdao.getAll();
      hpModel = new HocPhanTableModel(dsHp);
      hocPhanTb.setModel(hpModel);
      Vector<HocPhan> dsHpVector = new Vector<>(dsHp);
      dsHpVector.add(0, null);
      DefaultComboBoxModel<HocPhan> hpComboModel = new DefaultComboBoxModel<>(dsHpVector);
      mahptdCombo.setModel(hpComboModel);
      mahptdCombo.setSelectedIndex(0);
      dsNganhCB = new ArrayList<>();
      dsNganh=ndao.getAll();
      dsNganh.forEach(n -> dsNganhCB.add(new JCheckBox(n.toString())));
      cnList.removeAll();
      dsNganhCB.forEach(cb->cnList.add(cb));
      filterByCombo.setModel(new DefaultComboBoxModel<>(new Vector(hpModel.getHeaders())));
      rowSorter = new TableRowSorter<>(hpModel);
      hocPhanTb.setRowSorter(rowSorter);
    } catch (SQLException ex) {
      MessageBox.showErrorMessage(this, ex.getMessage());
    }
  }

  private void onFiltering() {
    rowSorter.setRowFilter(RowFilter.regexFilter(keyTf.getText(), filterByCombo.getSelectedIndex()));
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
   * content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    mahpTf = new javax.swing.JTextField();
    mahptdCombo = new javax.swing.JComboBox<>();
    tenhpTf = new javax.swing.JTextField();
    motaTf = new javax.swing.JTextField();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    jLabel13 = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    sotcSpinner = new javax.swing.JSpinner();
    ppdgTf = new javax.swing.JTextField();
    batBuocCheckbox = new javax.swing.JCheckBox();
    jScrollPane3 = new javax.swing.JScrollPane();
    cnList = new javax.swing.JPanel();
    jPanel4 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jPanel5 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    filterByCombo = new javax.swing.JComboBox<>();
    keyTf = new javax.swing.JTextField();
    jScrollPane2 = new javax.swing.JScrollPane();
    hocPhanTb = new ui.WithTooltipTable();
    jPanel2 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();

    jLabel3.setText("Mã học phần:");

    jLabel6.setText("Mã học phần tiền đề:");

    jLabel4.setText("Tên học phần:");

    jLabel5.setText("Mô tả:");

    motaTf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        motaTfActionPerformed(evt);
      }
    });

    jLabel11.setText("Phương pháp đánh giá:");

    jLabel12.setText("Chuyên ngành:");

    jLabel13.setText("Số tín chỉ:");

    jLabel14.setText("Bắt buộc:");

    batBuocCheckbox.setText("Học phần này bắt buộc");
    batBuocCheckbox.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        batBuocCheckboxActionPerformed(evt);
      }
    });

    cnList.setLayout(new javax.swing.BoxLayout(cnList, javax.swing.BoxLayout.Y_AXIS));
    jScrollPane3.setViewportView(cnList);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel5)
              .addComponent(jLabel13))
            .addGap(79, 79, 79)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(motaTf, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
              .addComponent(sotcSpinner)))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel6)
              .addComponent(jLabel3)
              .addComponent(jLabel4))
            .addGap(19, 19, 19)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(mahpTf, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
              .addComponent(mahptdCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(tenhpTf))))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(53, 53, 53))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(ppdgTf, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(2, 2, 2)
            .addComponent(jLabel14)
            .addGap(82, 82, 82)
            .addComponent(batBuocCheckbox)))
        .addGap(20, 20, 20))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(ppdgTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel11))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(3, 3, 3)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel3)
              .addComponent(mahpTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jLabel6))
                  .addComponent(mahptdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addGroup(jPanel3Layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addGap(3, 3, 3))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tenhpTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(8, 8, 8)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel5)
              .addComponent(motaTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabel13)
            .addComponent(sotcSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(batBuocCheckbox)
            .addComponent(jLabel14)))
        .addContainerGap(14, Short.MAX_VALUE))
    );

    jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/add.png"))); // NOI18N
    jButton1.setText("Thêm");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    jPanel4.add(jButton1);

    jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/edit.png"))); // NOI18N
    jButton2.setText("Sửa");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });
    jPanel4.add(jButton2);

    jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/remove.png"))); // NOI18N
    jButton3.setText("Xóa");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });
    jPanel4.add(jButton3);

    jButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/refresh.png"))); // NOI18N
    jButton5.setText("Làm mới");
    jButton5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton5ActionPerformed(evt);
      }
    });
    jPanel4.add(jButton5);

    jLabel1.setText("Tìm kiếm:");
    jPanel5.add(jLabel1);
    jPanel5.add(filterByCombo);

    keyTf.setColumns(10);
    jPanel5.add(keyTf);

    hocPhanTb.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Ma hoc phan", "Title 2", "Title 3", "Title 4"
      }
    ));
    hocPhanTb.setShowGrid(true);
    jScrollPane2.setViewportView(hocPhanTb);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        .addGap(20, 20, 20))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel2.setText("QUẢN LÝ HỌC PHẦN");
    jPanel2.add(jLabel2);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
          .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void refresh() {
    load();
    mahpTf.setText("");
    mahptdCombo.setSelectedIndex(0);
    tenhpTf.setText("");
    motaTf.setText("");
    ppdgTf.setText("");
    sotcSpinner.setValue(0);
    batBuocCheckbox.setSelected(false);
    mahpTf.setEnabled(true);
  }
  private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    refresh();
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton5ActionPerformed

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    if (hocPhanTb.getSelectedRow() == -1) {
      MessageBox.showErrorMessage(this, "Chọn một hàng để xóa!");
      return;
    }
    try {
      HocPhan hp = new HocPhan();
      hp.setMaHP(mahpTf.getText());
      if (MessageBox.showConfirmDialog(this, "Xác nhận xóa?")) {
        ctdao.delete(new ChuongTrinh(null, hp));
        hpdao.delete(hp);
        refresh();
      }
    } catch (Exception e) {
      MessageBox.showErrorMessage(this, e.getMessage());
    }
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton3ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try {
      HocPhan hp = getHocPhanFromForm();
      hpdao.update(hp);
      ctdao.delete(new ChuongTrinh(null, hp));
      ctdao.add(hp.getDsNganh().stream().map(n->new ChuongTrinh(n, hp)).collect(Collectors.toList()));
      refresh();
    } catch (Exception e) {
      MessageBox.showErrorMessage(this, e.getMessage());
    }
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton2ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
      HocPhan hp = getHocPhanFromForm();
      hpdao.add(hp);
      ctdao.add(hp.getDsNganh().stream().map(n->new ChuongTrinh(n, hp)).collect(Collectors.toList()));
      refresh();
    } catch (Exception e) {
      String mess = e.getMessage();
      if (e instanceof SQLException) {
        mess = "Mã học phần đã tồn tại!";
      }
      MessageBox.showErrorMessage(this, mess);
      e.printStackTrace();
    }
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton1ActionPerformed

  private void batBuocCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batBuocCheckboxActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_batBuocCheckboxActionPerformed

  private void motaTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motaTfActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_motaTfActionPerformed

  private HocPhan getHocPhanFromForm() {
    HocPhan hp = new HocPhan();
    hp.setMaHP(mahpTf.getText());
    hp.setHptd((HocPhan) mahptdCombo.getSelectedItem());
    hp.setTenHP(tenhpTf.getText());
    hp.setMoTa(motaTf.getText());
    hp.setPpdg(ppdgTf.getText());
    hp.setBatBuoc(batBuocCheckbox.isSelected());
    hp.setSoTC((int) sotcSpinner.getValue());
    List<Nganh> dsn=new ArrayList<>();
    for(int i=0;i<dsNganhCB.size();++i){
      if(dsNganhCB.get(i).isSelected()){
        dsn.add(dsNganh.get(i));
      }
    }
    hp.setDsNganh(dsn);
    return hp;
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JCheckBox batBuocCheckbox;
  private javax.swing.JPanel cnList;
  private javax.swing.JComboBox<String> filterByCombo;
  private ui.WithTooltipTable hocPhanTb;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton5;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JTextField keyTf;
  private javax.swing.JTextField mahpTf;
  private javax.swing.JComboBox<HocPhan> mahptdCombo;
  private javax.swing.JTextField motaTf;
  private javax.swing.JTextField ppdgTf;
  private javax.swing.JSpinner sotcSpinner;
  private javax.swing.JTextField tenhpTf;
  // End of variables declaration//GEN-END:variables
}
